Website = "https://gegenlicht.net"

[Details]
  Icon = "img/Icon.png"
  Name = "movie-transfer-preperation-tool"
  ID = "net.gegenlicht.movie-transfer-preperation-tool"
  Version = "0.1.0"
  Build = 7
