name: build-linux-release
run-name: Building Releases of ${{ github.repository }}
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: WillAbides/setup-go-faster@v1.5.0
        with:
          go-version: 1.20

      - name: Get dependencies
        run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev

      - name: Get Golang dependencies
        run: go get -v -t -d ./...

      - name: Build for Linux
        run: go build -o movieTransferPreparationTool -ldflags "-s -w" ./...

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Linux Executable
          path: movieTransferPreparationTool

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o movieTransferPreparationTool.exe -ldflags "-s -w" ./...

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Windows Executable
          path: movieTransferPreparationTool.exe

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: false
          files: |
            movieTransferPreparationTool
            movieTransferPreparationTool.exe
      
